config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "groups#index"
  resources :users, only:[:index, :edit, :update]
  resources :groups, only:[:new, :create, :edit, :update] do
     resources :messages, only: [:index, :create]
      namespace :api do
        resources :messages, only: :index, defaults: { format: 'json' }
    end
  end
end

app/models/message.rb
class Message < ApplicationRecord
  mount_uploader :image, ImageUploader

  belongs_to :user
  belongs_to :group
  
  validates :content, presence: true, unless: :image?
end

app/controllers/api/messages_controller.rb
class Api::MessagesController < ApplicationController
  def index
    @group = Group.find(params[:group_id]) 
    @messages = @group.messages.includes(:user).where('id > ?', params[:last_id]) 
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group

  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)
  end

  def create
    @message = @group.messages.new(message_params)
    if @message.save
      respond_to do |format|
        format.html {redirect_to group_messages_path(@group), notice: 'メッセージが送信されました'}
        format.json
      end
    else
      @messages = @group.messages.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください。'
      render :index
    end
  end

  private
  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/views/messages/_main_chat.html.haml
.main-chat
  .chat-header
    .chat_group-name
      %h2
        = @group.name
      .chat-member
        %p Members: 
        .chat-member_name
          - @group.users.each do |user,index|
            %h3 
              = user.name
    .chat_edit
      = link_to edit_group_path(@group) do
        %p Edit
  .chat-content
    = render @messages
  .form
    = form_for([@group, @message],id: "new-comment") do |f|
      .form-action
        .form-position
          = f.text_field :content, class: "chat_form-text", placeholder: "type a message"
          = f.label :image, class: 'form__mask__image' do
            = icon('fa', 'image', class: 'fa-image')
            = f.file_field :image, class: 'file-input'
        .fore-submit
          = f.submit 'Send', class: "submit_btn"

app/views/messages/_message.html.haml
.message{"data-message_id": "#{message.id}"}
  .upper-message
    .chat_user-name
      = message.user.name
    .day-time
      = message.created_at.strftime("%Y/%m/%d(%a) %H:%M")
  .chat-message
    - if message.content.present?
      %p.lower-message__content
        = message.content
    = image_tag message.image.url, class: 'lower-message__image' if message.image.present?

app/views/messages/_side_bar.html.haml
%body
  = render "devise/shared/side_bar"

app/views/messages/index.html.haml
.flash-box
  .nitice
.wrapper
  = render partial: "side_bar"
  = render partial: "main_chat"